import { RegistryItemSchema, RegistryType } from "./types";

type ComponentType = Omit<
  RegistryItemSchema,
  "$schema" | "files" | "type" | "author"
> &
  Partial<Pick<RegistryItemSchema, "type" | "author">> & {
    path: string;
    files?: {
      path: string;
      name: string;
      content: string;
      type: RegistryType;
    }[];
  };

// Static component list - this is auto-generated by the build script
export const components: ComponentType[] = [
  {
    name: "accordion",
    title: "Accordion",
    description: "A minimalistic accordion component designed with React and Tailwind CSS.",
    path: "../app/docs/accordion",
    dependencies: [],
  },
  {
    name: "accordion-last",
    title: "Accordion Last",
    description: "A minimalistic accordion component with last item styling designed with React and Tailwind CSS.",
    path: "../app/docs/accordion-last",
    dependencies: [],
  },
  {
    name: "amazongift",
    title: "Amazongift",
    description: "A minimalistic Amazon gift card component designed with React and Tailwind CSS.",
    path: "../app/docs/amazongift",
    dependencies: [],
  },
  {
    name: "button",
    title: "Button",
    description: "A minimalistic button component designed with React and Tailwind CSS.",
    path: "../app/docs/button",
    dependencies: [],
  },
  {
    name: "card",
    title: "Card",
    description: "A minimalistic card component designed with React and Tailwind CSS.",
    path: "../app/docs/card",
    dependencies: [],
  },
  {
    name: "dock",
    title: "Dock",
    description: "A minimalistic dock component designed with React and Tailwind CSS.",
    path: "../app/docs/dock",
    dependencies: [],
  },
  {
    name: "dropdown",
    title: "Dropdown",
    description: "A minimalistic dropdown component designed with React and Tailwind CSS.",
    path: "../app/docs/dropdown",
    dependencies: [],
  },
  {
    name: "flipwords",
    title: "Flipwords",
    description: "A minimalistic flip words animation component designed with React and Tailwind CSS.",
    path: "../app/docs/flipwords",
    dependencies: [],
  },
  {
    name: "fuzzy",
    title: "Fuzzy",
    description: "A minimalistic fuzzy search component designed with React and Tailwind CSS.",
    path: "../app/docs/fuzzy",
    dependencies: [],
  },
  {
    name: "login",
    title: "Login",
    description: "A minimalistic login component designed with React and Tailwind CSS.",
    path: "../app/docs/login",
    dependencies: [],
  },
  {
    name: "password",
    title: "Password",
    description: "A minimalistic password input component designed with React and Tailwind CSS.",
    path: "../app/docs/password",
    dependencies: [],
  },
  {
    name: "pattern",
    title: "Pattern",
    description: "A collection of beautiful background patterns designed with React and Tailwind CSS.",
    path: "../app/docs/pattern",
    dependencies: [],
  },
  {
    name: "prompt",
    title: "Prompt",
    description: "A minimalistic prompt component designed with React and Tailwind CSS.",
    path: "../app/docs/prompt",
    dependencies: [],
  },
  {
    name: "search",
    title: "Search",
    description: "A minimalistic search component designed with React and Tailwind CSS.",
    path: "../app/docs/search",
    dependencies: [],
  },
  {
    name: "tabs",
    title: "Tabs",
    description: "A minimalistic tab component designed with React and Tailwind CSS.",
    path: "../components/core/tabs.tsx",
    dependencies: [],
  },
  {
    name: "tabs-classic",
    title: "Tabs Classic",
    description: "A minimalistic tabs classic component designed with React and Tailwind CSS.",
    path: "../app/docs/tabs-classic",
    dependencies: [],
  },
  {
    name: "tabs-fancy",
    title: "Tabs Fancy",
    description: "A minimalistic tabs fancy component designed with React and Tailwind CSS.",
    path: "../app/docs/tabs-fancy",
    dependencies: [],
  },
  {
    name: "twostep",
    title: "Twostep",
    description: "A minimalistic two-step verification component designed with React and Tailwind CSS.",
    path: "../app/docs/twostep",
    dependencies: [],
  }
];
